name: '🐛 Integration issue'
labels: ['bug']
description: 'The integration is discontinued? Is it no longer relevant/compatible? Let us know'

body:
  - type: textarea
    attributes:
      label: Problem
      description: Describe the issue here
    validations:
      required: true

  - type: textarea
    attributes:
      label: References
      label: Reference any relevant documentation, other materials or issues/pull requests
